Switching to Community-Spec-1.0 for specification license
SBOMit/specification pull request #14
Opened 2023-08-25 15:45 UTC by idunbarh

See issue !13.

LF started IP/License review of SBOMit for the OpenSSF sandbox application, and [requested we switch the license of the spec to Community Specification License 1.0](https://github.com/ossf/tac/issues/191#issuecomment-1692546537)

See https://github.com/CommunitySpecification/Community_Specification/blob/main/1._Community_Specification_License-v1.md
This is required by the OpenSSF Charter (Section 5, Page 9):
https://cdn.platform.linuxfoundation.org/agreements/openssf.pdf

2023-08-25 15:57 UTC, trishankatdatadog approved these changes

2023-08-25 16:40 UTC, sudo-bmitch commented
Does this require getting signoff from all committers to the project (to change the license they used with their contributions)?

2023-08-25 21:39 UTC, colek42 commented
lgtm

2023-08-26 04:23 UTC, JustinCappos requested changes
For now, do not merge this PR!

There is still a discussion ongoing and some of our early folks were very opposed to this license.  I'm following up with the OpenSSF in the linked issue on their tracker.

2023-08-26 15:42 UTC, idunbarh commented
Switching to draft to ensure its not merged until licensing until discussion with LF and maintainers is resolved.

2023-09-07 03:01 UTC, idunbarh commented
@JustinCappos thoughts on this PR? We have support from @mnm678 @colek42 and @trishankatdatadog.

2023-09-07 15:47 UTC, trishankatdatadog approved these changes

2023-09-08 15:29 UTC, JustinCappos commented
Had a great conversation with Mike Dolan and Jory about the details here.  We can merge!

2023-09-08 15:30 UTC, JustinCappos approved these changes

2023-09-08 15:30 UTC, merged

2023-09-08 16:36 UTC, idunbarh commented
resolves #13